name: luxai_s2
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - matplotlib
  - scipy
  - pip
  - cython
  - tqdm
  - yaml
  - gym=0.21

  - pip:
    - pettingzoo==1.12.0
    - termcolor
    - pygame
    - vec_noise

